## Python_Notes_015

### List Comprehension
It is an easy and compact syntax for creatng a list from a string or another iterable.
It performs an operaton on each item in the existing object.
It is consderably faster than processng with a lambda function or loop.
It was added in Python 2.0 from patches by Greg Ewing with contributions by Skip Montanaro and Thomas Wouters.

In [1]:
# Simple list comprehension.
word_1 = 'Python is easy'
alphabets_1 = [letter for letter in word_1]
print(alphabets_1)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'e', 'a', 's', 'y']


In [2]:
# Using lambda.
word_2 = 'Python is easy'
func_1 = lambda letter: letter
alphabets_2 = map(func_1, word_2)
print(list(alphabets_2))

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'e', 'a', 's', 'y']


In [3]:
# Using loop.
word_3 = 'Python is eazy'
alphabets_3 = []
for letter in word_3:
    alphabets_3.append(letter)
print(alphabets_3)

['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'e', 'a', 'z', 'y']


In [4]:
# Time list comprehension.
import time
start_1 = time.time()

numbers_1 = range(1, 100001)
result_1 = (sum([x**5 for x in numbers_1]))**0.5 / sum(numbers_1)
print(f'The result is: {round(result_1, 4)}')

end_1 = time.time()
print(f'Total time is: {round(end_1 - start_1, 4)}')

The result is: 81650.0663
Total time is: 0.0441


In [5]:
# Time lambda
import time
start_2 = time.time()

numbers_2 = range(1, 100001)
func_2 = lambda x: x**5
evaluate_2 = map(func_2, numbers_2)
result_2 = (sum(evaluate_2))**0.5 / sum(numbers_2)
print(f'The result is: {round(result_2, 4)}')

end_2 = time.time()
print(f'Total time is: {round(end_2 - start_2, 4)}')

The result is: 81650.0663
Total time is: 0.0529


In [6]:
# Time loop.
import time
start_3 = time.time()

numbers_3 = range(1, 100001)
evaluate_3 = []
for x in numbers_3:
    first_3 = x**5
    evaluate_3.append(first_3)
    
result_3 = (sum(evaluate_3))**0.5 / sum(numbers_3)
print(f'The result is: {round(result_3, 4)}')

end_3 = time.time()
print(f'Total time is: {round(end_3 - start_3, 4)}')

The result is: 81650.0663
Total time is: 0.0652


In [7]:
# List comprehension with if.
lc_if = [x for x in range(1,21) if x % 2 == 0] # The condition comes after the iterator.
print(lc_if)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [8]:
# List comprehension with several ifs.
lc_moreif = [x for x in range(1,21) if x != 1 if x % 2 != 0 if x % 3 != 0] # This should result in prime numbers.
print(lc_moreif)

[5, 7, 11, 13, 17, 19]


In [9]:
# List comprehension with several if & and.
lc_if_and = [x for x in range(1,21) if x != 1 and x % 2 != 0 and x % 3 != 0] # This should result in prime numbers.
print(lc_if_and)

[5, 7, 11, 13, 17, 19]


In [10]:
# List comprehension with if, else.
lc_if_else = ['Even' if num % 2 == 0 else 'Odd' for num in range(1, 11)] # The conditions comes befor the iterator.
print(lc_if_else)

['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even']


In [11]:
# List comprehension with if, else, if.
lc_if_else_if = [x if x > 4 else '*' for x in range(1, 21) if x % 2 == 0]
print(lc_if_else_if)

['*', '*', 6, 8, 10, 12, 14, 16, 18, 20]


In [12]:
# list comprehension vector transpose
vector = [[2, 4, 6, 8]]
matrix = [[row[i] for row in vector] for i in range(4)]
print(matrix)

[[2], [4], [6], [8]]


In [13]:
# list comprehension matrix transpose.
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_2 = [[row[i] for row in matrix_1] for i in range(3)]
print(matrix_2)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [14]:
# Cornfirm with numpy transpose.
import numpy
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_3 = numpy.transpose(matrix_1)
print(matrix_3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [15]:
# Check if matrix_2 and matrix_3 are equal.
matrix_2 == matrix_3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
# Check if matrix_1 and matrix_3 are equal.
matrix_1 == matrix_3

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])